import { createHmac, timingSafeEqual } from 'node:crypto';
import { resolve } from 'node:path';
import { env } from '../config/env.js';

/**
 * Signed upload URLs are the load-bearing SSRF gate for the vision pipeline
 * (ARCH §7). The vision tool refuses any URL it didn't mint here.
 *
 * Wire format: `signed:<base64url(payload)>.<base64url(hmac)>` where
 *   payload = JSON({ filename, exp })
 *   hmac    = HMAC-SHA256(payload, env.IP_HASH_SALT)
 *
 * The filename is bound by the signature, so an attacker can't shuffle a
 * valid HMAC onto a different file. `exp` is checked at verify time.
 *
 * NOTE on key reuse: we re-use `IP_HASH_SALT` as the upload-signing key for
 * Cycle 4 (documented in cycle-4.md). Cycle 6 introduces a dedicated
 * `UPLOAD_SIGNING_SECRET` env var and rotates this off the shared salt.
 */

const SCHEME = 'signed:';

interface Payload {
  filename: string;
  exp: number; // ms since epoch
}

function b64url(buf: Buffer): string {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
}

function unb64url(s: string): Buffer {
  // Pad back to a multiple of 4.
  const padded = s.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4 === 0 ? '' : '='.repeat(4 - (padded.length % 4));
  return Buffer.from(padded + pad, 'base64');
}

function sign(payload: string): string {
  return b64url(createHmac('sha256', env.IP_HASH_SALT).update(payload).digest());
}

export function signUploadUrl(filename: string, ttlMs: number): string {
  if (!filename || /[\\/]/.test(filename)) {
    // Defensive — filename is generated by us as a `<nanoid>.<ext>`, no path
    // separators allowed. The signature would still bind it, but a clean
    // refusal here surfaces the bug earlier.
    throw new Error('signUploadUrl: filename must be a bare basename');
  }
  const exp = Date.now() + ttlMs;
  const payload: Payload = { filename, exp };
  const json = JSON.stringify(payload);
  const encoded = b64url(Buffer.from(json, 'utf8'));
  const mac = sign(encoded);
  return `${SCHEME}${encoded}.${mac}`;
}

export interface VerifiedUpload {
  localPath: string;
  filename: string;
  exp: number;
}

/**
 * Returns `null` on any failure: scheme mismatch, malformed token, HMAC
 * mismatch, expired, or filename traversal. Callers MUST treat null as a
 * hard refusal and surface a clear tool_error to the LLM.
 */
export function verifyUploadUrl(url: string): VerifiedUpload | null {
  if (typeof url !== 'string' || !url.startsWith(SCHEME)) return null;
  const body = url.slice(SCHEME.length);
  const dot = body.lastIndexOf('.');
  if (dot <= 0 || dot === body.length - 1) return null;

  const encoded = body.slice(0, dot);
  const supplied = body.slice(dot + 1);

  const expectedMac = sign(encoded);
  const a = Buffer.from(expectedMac);
  const b = Buffer.from(supplied);
  if (a.length !== b.length) return null;
  if (!timingSafeEqual(a, b)) return null;

  let payload: Payload;
  try {
    payload = JSON.parse(unb64url(encoded).toString('utf8')) as Payload;
  } catch {
    return null;
  }
  if (
    !payload ||
    typeof payload.filename !== 'string' ||
    typeof payload.exp !== 'number' ||
    /[\\/]/.test(payload.filename) ||
    payload.filename.startsWith('.')
  ) {
    return null;
  }
  if (payload.exp < Date.now()) return null;

  // Resolve under UPLOAD_DIR; refuse if the resolved path escapes the dir
  // (belt-and-braces — the earlier filename check already prevents this).
  const root = resolve(env.UPLOAD_DIR);
  const localPath = resolve(root, payload.filename);
  if (!localPath.startsWith(root + '/') && localPath !== root) return null;

  return { localPath, filename: payload.filename, exp: payload.exp };
}
